CREATE TABLE public.user_settings (
    user_id uuid NOT NULL DEFAULT auth.uid(),
    settings jsonb,
    updated_at bigint,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.sync_meta (
    min_compatible_version integer NOT NULL,
    PRIMARY KEY (min_compatible_version)
);

CREATE TABLE public.dictionary_words (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    japanese text,
    hiragana text,
    chinese text,
    level text,
    pos text,
    example_1 text,
    gloss_1 text,
    example_2 text,
    gloss_2 text,
    example_3 text,
    gloss_3 text,
    is_delisted boolean DEFAULT false,
    updated_at timestamp with time zone DEFAULT now(),
    raw_id text,
    created_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE public.dictionary_grammars (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    raw_id text,
    level text,
    title text,
    content jsonb,
    is_delisted boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);

CREATE TABLE public.dictionary_meta (
    id integer NOT NULL,
    words_version integer DEFAULT 1,
    grammars_version integer DEFAULT 1,
    words_updated_at timestamp with time zone,
    grammars_updated_at timestamp with time zone,
    updated_at timestamp with time zone DEFAULT now(),
    PRIMARY KEY (id)
);
